package cn.itsource.model;

public class News {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.id
     *
     * @mbg.generated Fri Jun 21 15:57:31 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.name
     *
     * @mbg.generated Fri Jun 21 15:57:31 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.pwd
     *
     * @mbg.generated Fri Jun 21 15:57:31 CST 2019
     */
    private String pwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.id
     *
     * @return the value of t_news.id
     *
     * @mbg.generated Fri Jun 21 15:57:31 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.id
     *
     * @param id the value for t_news.id
     *
     * @mbg.generated Fri Jun 21 15:57:31 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.name
     *
     * @return the value of t_news.name
     *
     * @mbg.generated Fri Jun 21 15:57:31 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.name
     *
     * @param name the value for t_news.name
     *
     * @mbg.generated Fri Jun 21 15:57:31 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.pwd
     *
     * @return the value of t_news.pwd
     *
     * @mbg.generated Fri Jun 21 15:57:31 CST 2019
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.pwd
     *
     * @param pwd the value for t_news.pwd
     *
     * @mbg.generated Fri Jun 21 15:57:31 CST 2019
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }
}